{% set name = "csp-adapter-slack" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/csp-adapter-slack/csp_adapter_slack-{{ version }}.tar.gz
  sha256: 39ec2d61459835d31274a554d595a5457aa08337922d9b261fc6c77847a839b3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - csp
    - slack-sdk >=3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp_adapter_slack

about:
  home: http://github.com/point72/csp-adapter-slack
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A csp adapter for slack
  description: A csp adapter for slack
  dev_url: http://github.com/point72/csp-adapter-slack

extra:
  recipe-maintainers:
    - timkpaine
